### PR TITLE
Added API methods and fixed Kerberos authentication

### PR DESCRIPTION
**Pull request by mcb64**
Added API methods to add a new hutch and get the configuration values.  Also fixed a kerberos authentication issue.

### CODE REVIEW

**Review by ZLLentz — APPROVED** [review]
Looks good to me

**Comment by ZLLentz** [comment]
@mcb64 should I mirror the master branch after this tag as `R2.1.1` for conda?

**Comment by mcb64** [comment]
Yes, and then we are synced.  I agree, we need to be more careful in the future.  Blame for everyone! ;-)

**Comment by mcb64** [comment]
Moving forward, I shouldn't do local releases until I pull the tags from upstream.  I shouldn't be making local tags... at least not Rx.y.z.  Maybe Rx.y.z-q.

**Pull request merged**
