### PR TITLE
MNT: noarch, py3.7+

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

- Update travis config to the shared configurations
- Make the package noarch and allow new python versions
- Allow usage with newest tag of mysqlclient

## Motivation and Context

- related to https://github.com/pcdshub/pcds-envs/issues/87

## How Has This Been Tested?

- Hopefully the CI passes

### CODE REVIEW

**Comment by ZLLentz** [comment]
Oh boy, we've got a conda spasm here. What a shame. I'll mark this as a draft and dismiss the review requests for now.

**Comment by klauer** [comment]
Oh no...

**Comment by ZLLentz** [comment]
I think this is because of the very specific version of mysqlclient that pmgr uses is not available on conda-forge, is only built through python=3.6 on defaults (which aren't valid channels in the standard build), and is only built through python=3.7 on pcds-tag, but this build tried to build using python=3.8

I'll let this sit a bit to try to think up a reasonable solution...

**Comment by ZLLentz** [comment]
I think the only reasonable approaches are to either:
- Modify/update to not require such a specific version
- Build and upload py3.8, py3.9 versions ourselves

**Comment by klauer** [comment]
For the two proposed options:
1. Any idea how much of an API change there is with later mysqlclient versions? There's only 34 lines in the entire repo that refer to sql, which seems a good sign.
2. pmgr has hardly seen any updates recently, so building and uploading would probably be a once-and-done sort of thing (hopefully).

It'd be nicer to do (1), but not sure about the time investment required or if it's worth it.

**Comment by ZLLentz** [comment]
I'm going to give a quick try with pmgr in a python environment with the newest version of mysqlclient, see if I can at least read from a database without crashing

**Comment by ZLLentz** [comment]
Looks like we get lucky; just one API change that I could see! And it's just a basic "we moved the location of the exceptions classes from a strange place to a normal place". I was able to read the database, create a test object, close and reload, see my test object, and delete it.

I'll make a relevant patch here and assume that "nothing could go wrong" until proven otherwise

**Comment by klauer** [comment]
Woohoo! 👏

**Review by klauer — APPROVED** [review]

**Pull request merged**
